apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ${APP_NAME}-backend-config
spec:
  timeoutSec: 90
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    type: HTTP
    requestPath: /