apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: gcr.io/${PROJECT_ID}/${REPO_NAME}-java:${TAG_NAME}
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "scheduler,mongo,changeStream"
        - name: DATABASE_PASSWORD
          value: "${DATABASE_PASSWORD}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources:
          limits:
            cpu: 900m
            memory: 1G
          requests:
            cpu: 800m
            memory: 800m
        livenessProbe:
          initialDelaySeconds: 50
          httpGet:
            path: /actuator/health
            port: 8081
        readinessProbe:
          initialDelaySeconds: 50
          httpGet:
            path: /actuator/health
            port: 8081