apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: gcr.io/${PROJECT_ID}/${REPO_NAME}:${TAG_NAME}
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "${ACTIVE_PROFILE}"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "mysogno-${ACTIVE_PROFILE}"
              key: db
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources:
          limits:
            cpu: 800m
            memory: 1G
          requests:
            cpu: 600m
            memory: 800m
        livenessProbe:
          initialDelaySeconds: 50
          httpGet:
            path: /actuator/health
            port: 8081
        readinessProbe:
          initialDelaySeconds: 50
          httpGet:
            path: /actuator/health
            port: 8081