apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
  annotations:
   cloud.google.com/backend-config: '{"default": "${APP_NAME}-backend-config"}'
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
  ports:
  - port: 8080
    targetPort: 8080
    name: web
  - port: 8081
    targetPort: 8081
    name: management