spring:
  data:
    mongodb:
      uri: "mongodb+srv://admin:admin12345@demo.uskpz.mongodb.net/mongodb-java"
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
settings:
  #App thread pool setting
  corePoolsize: 10 
  maxPoolSize: 30
  queueSize: 100000