steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ["-c", 'docker pull gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA || exit 0']
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/kubectl"
    entrypoint: bash
    args: 
    - '-c'
    - |
      sed -i -e 's/$${PROJECT_ID}/$PROJECT_ID/g' -e 's/$${REPO_NAME}/$REPO_NAME/g' -e 's/$${APP_NAME}/${REPO_NAME}/g' -e 's/$${TAG_NAME}/$COMMIT_SHA/g' -e 's/$${MIN_REPLICAS}/${_MIN_REPLICAS}/g' -e 's/$${MAX_REPLICAS}/${_MAX_REPLICAS}/g' gke/*.yaml
      gcloud container clusters get-credentials --project="$PROJECT_ID" --zone="${_ZONE}" "${_CLUSTER}"
      kubectl apply -f gke/
    env:
    - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
    - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["set", "image", "deployment", "${REPO_NAME}", "${REPO_NAME}=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
    env:
    - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
    - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"
images: ["gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
